### ISSUE TITLE
[SUGGESTION] WZS: Restrict the Hammer to Members only

### ISSUE THREAD

**Issue by Loickun** [Azurblau/Zombies.Zone#12]
Hello! 
Not sure how this works but, here we go.
The title tells it already. Giving the Hammer only to players who have spent some fair time on the Server would end in less prop piels and shitcades. I know, shit cade is better than no cade but still! 
It's really time consuming when you are trying to cade and noodle people while they are running around, trying to read their name. ( I dont want to punish innocent people and I know i can use !unnonail and such)

yours sincerly
Loic

PS: Please excuse my bad english grammar >.<

**Comment by jems01** [comment]
What happens if there's no members online?

Everyone starts somewhere, how can you get better if you can't even get a hammer until level 30?

Also, just because someone is a member doesn't necessarily mean they can cade, I understand that it would limit a lot of players from cading, and that most are < level 30. How would you combat this?

**Comment by Loickun** [comment]
I have a better idea! 
How about changing the player name position from the floor/feet and put it above their head  or make names on nails abit brighter or more visible. Or change it so that you can see the names of people who nailed something near you on your screen on the right side maybe >.<

**Comment by jems01** [comment]
Hmm, I like it. Make names high visibility depending on who your crosshair is looking at? x3

That would make it much easier to see who's offending, and / or we could have a system which highlighted someone's name a different colour when they're picking up a prop?

**Comment by Loickun** [comment]
YES! That sounds already really great to work with! But then again, when there are tons of people in a thight place might be difficult to put the crosshair on the right one. But still would improve  alot on now days work as a bouncer :3

**Comment by Azurblau** [comment]
Picking up props currently uses a system that forbids picking up below a certain level if no high level player is carrying a hammer. Back then I already was thinking about adding that same system for using hammer, however, there is one problem: What if a newbie bought a hammer, and a high-level person shortly after? Will the newbie have wasted his points? I also can't refund the points either because some maps provide hammer to be picked up.

One other idea I had was to prevent newbies from nailing near nails of high level players. Or just prevent nailing on props already nailed by a higher level player. These might work, but I'm waiting for more ideas or opinions on this one. I might start working on it next weekend.

**Comment by TheFray89** [comment]
For me is No.
as jems said, if no members are online literally no one can cade properly.

**Comment by Azurblau** [comment]
Players below level 20 can no longer nail props already nailed by a higher level player.
