### ISSUE TITLE
[BUGS]WZS: Server #3

### ISSUE THREAD

**Issue by v1red** [Azurblau/Zombies.Zone#156]
BUGS:

-Some players with lower level can join and play https://imgur.com/qevEkMG 
-Knockback of turrets massive for weapons like oppresor/chalanger/sage.Class like poison zombie and zombine cant even get close to cade or the end up flying all over map.
-Some props become invisible like doors and plastic basckets/wooden barrels(map summer keep) when u pick them up aswell.
-The brightness on MTL defence inside... fucking hell its bad.

**Comment by h4uja2** [comment]
> -Some players with lower level can join and play https://imgur.com/qevEkMG

They will be redirected to #1 after some time

> -Knockback of turrets massive for weapons like oppresor/chalanger/sage.Class like poison zombie and zombine cant even get close to cade or the end up flying all over map.

Are these weapons even turret mountable?

> -Some props become invisible like doors and plastic basckets/wooden barrels(map summer keep) when u pick them up aswell.

Happens because some props' materials use `$alphatest 1` to cut some parts, and it's not compatible with `$alpha 1`/`$translucent 1`

> -The brightness on MTL defence inside... fucking hell its bad.
Map author didn't generate cubemaps and configure HDR properly, so the only way to fix this is to disable bloom/hdr in video settings

**Comment by jems01** [comment]
Individual bugs need their own post. Please open a ticket for each one.
